/**
 * The Love Letter server: Node http serving the client build, plus a raw
 * WebSocket upgrade at `/ws`. The server is a thin relay over the engine:
 * sockets send packets, the server stamps the acting playerId, the engine
 * validates and applies, and the resulting events are broadcast.
 *
 * Room registry: `Map<roomCode, Room>`; a Room holds the authoritative engine
 * state, its sockets, the event log, and the chat log. `playerRooms` maps a
 * playerId back to their room so a dropped socket can `resume` its seat.
 *
 * Resilience (ticket 05, DESIGN Q12/Q14):
 *  - A socket drop starts a per-player grace window (`graceMs`, default 60s).
 *    If the dropped player's turn comes and they are still gone when the
 *    window expires, the server folds them out of the round (a system-issued
 *    engine intent); their seat stays for the next round. The last in-round
 *    player is never folded — instead the room is scheduled for expiry, so a
 *    returning player has one more window to revive it and nobody can stall.
 *  - `resume {playerId, lastEventId}` rebinds the seat to a new socket and
 *    replays every event after `lastEventId` from the authoritative log,
 *    filtered per-player so private card payloads never leak through replay.
 *  - A room whose last socket closed is deleted after one grace window unless
 *    someone resumes in the meantime.
 *  - `chat {text}` is relayed to the whole room and kept on a bounded chat
 *    log, resent as `chatLog` on resume.
 *
 * On join, a socket receives `hello` + `snapshot` (its private view); events
 * generated by its own join are sent to the pre-existing sockets instead, so
 * the new player never double-applies what the snapshot already contains.
 * Private events (`cardDealt`, `cardDrawn`) go only to the named player.
 */

import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { createServer } from 'node:http';
import { WebSocket, WebSocketServer } from 'ws';
import {
  apply,
  buildView,
  type ApplyResult,
  type ChatMessage,
  type ClientPacket,
  type Event,
  type GameState,
  type Intent,
  type ServerPacket,
  type WireParams,
} from '@love-letter/core';
import { serveStatic } from './static.js';

/** How long a dropped player's seat is held before folding / room cleanup. */
const DEFAULT_GRACE_MS = 60_000;
/** Longest chat message; the chat log keeps only this many lines. */
const MAX_CHAT_LENGTH = 200;
const MAX_CHAT_LINES = 200;

export interface Room {
  code: string;
  state: GameState | null;
  sockets: Map<string, WebSocket>;
  /** The authoritative, immutable event log; index = event id. */
  log: Event[];
  /** Room chat history, resent on resume. */
  chat: ChatMessage[];
  /** Dropped players still within their grace window: id → deadline (ms). */
  gone: Map<string, number>;
  /** Pending fold of the current turn owner, if any. */
  graceTimer: NodeJS.Timeout | null;
  /** Pending room cleanup once the last socket left. */
  expiryTimer: NodeJS.Timeout | null;
}

interface Connection {
  room: Room | null;
  playerId: string | null;
}

/** Everything the packet handlers need to mutate the world. */
interface ServerContext {
  rooms: Map<string, Room>;
  /** playerId → roomCode, so `resume` can find a seat without the code. */
  playerRooms: Map<string, string>;
  graceMs: number;
}

export interface AppHandle {
  httpServer: Server;
  /** The port actually bound (useful when created with port 0). */
  port: number;
  rooms: Map<string, Room>;
  close(): Promise<void>;
}

export interface AppOptions {
  port?: number;
  /** Directory to serve; pass null to serve nothing (ws-only). */
  staticRoot?: string | null;
  /** Seat-hold window after a socket drop (tests use a small value). */
  graceMs?: number;
}

export async function createApp(options: AppOptions = {}): Promise<AppHandle> {
  const { port = 3001, staticRoot = null, graceMs = DEFAULT_GRACE_MS } = options;
  const ctx: ServerContext = {
    rooms: new Map(),
    playerRooms: new Map(),
    graceMs,
  };

  const httpServer = createServer((req, res) => {
    if (staticRoot !== null) {
      void serveStatic(req, res, staticRoot);
    } else {
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('Not found');
    }
  });

  const wss = new WebSocketServer({ noServer: true });
  httpServer.on('upgrade', (req, socket, head) => {
    const pathname = new URL(req.url ?? '/', 'http://localhost').pathname;
    if (pathname === '/ws') {
      wss.handleUpgrade(req, socket, head, (ws) => wss.emit('connection', ws, req));
    } else {
      socket.destroy();
    }
  });

  wss.on('connection', (socket) => {
    const conn: Connection = { room: null, playerId: null };

    socket.on('message', (raw) => {
      let packet: ClientPacket;
      try {
        packet = JSON.parse(raw.toString()) as ClientPacket;
      } catch {
        sendError(socket, 'invalid_json');
        return;
      }
      handlePacket(ctx, conn, packet, socket);
    });

    socket.on('close', () => {
      if (conn.room === null || conn.playerId === null) return;
      const room = conn.room;
      const playerId = conn.playerId;
      // A newer resume may have replaced this socket as the player's live
      // connection — only unregister if we still are the current one. A room
      // already deleted (expired) is left alone; its teardown owns the rest.
      if (!ctx.rooms.has(room.code) || room.sockets.get(playerId) !== socket) return;
      markSeatGone(ctx, room, playerId);
      // The table must see the drop, not just the eventual fold (issue 11).
      announceGone(ctx, room, playerId);
    });
  });

  await new Promise<void>((resolve) => httpServer.listen(port, resolve));
  const address = httpServer.address();
  const actualPort = typeof address === 'object' && address !== null ? address.port : port;

  return {
    httpServer,
    port: actualPort,
    rooms: ctx.rooms,
    close: () => {
      for (const room of ctx.rooms.values()) {
        if (room.graceTimer !== null) clearTimeout(room.graceTimer);
        if (room.expiryTimer !== null) clearTimeout(room.expiryTimer);
        for (const ws of room.sockets.values()) ws.close();
      }
      ctx.rooms.clear();
      ctx.playerRooms.clear();
      return new Promise<void>((resolve) => {
        wss.close();
        httpServer.close(() => resolve());
      });
    },
  };
}

// ---------------------------------------------------------------------------
// Packet handling
// ---------------------------------------------------------------------------

function handlePacket(ctx: ServerContext, conn: Connection, packet: ClientPacket, socket: WebSocket): void {
  switch (packet.type) {
    case 'createRoom': return handleCreateRoom(ctx, conn, packet, socket);
    case 'joinRoom': return handleJoinRoom(ctx, conn, packet, socket);
    case 'playCard':
    case 'choice':
    case 'nextRound':
    case 'rematch':
      return handleGameIntent(ctx, conn, packet, socket);
    case 'leave': return handleLeave(ctx, conn, packet, socket);
    case 'resume': return handleResume(ctx, conn, packet, socket);
    case 'chat': return handleChat(conn, packet, socket);
    default:
      return sendError(socket, 'unknown_packet', { type: String((packet as { type?: unknown }).type) });
  }
}

function handleCreateRoom(
  ctx: ServerContext,
  conn: Connection,
  packet: Extract<ClientPacket, { type: 'createRoom' }>,
  socket: WebSocket,
): void {
  if (conn.room !== null) return sendError(socket, 'already_in_room');
  const code = generateRoomCode(ctx.rooms);
  const playerId = randomUUID();

  const result = apply(null, {
    type: 'createRoom',
    roomCode: code,
    capacity: packet.capacity as 2 | 3 | 4,
    playerId,
    playerName: packet.name,
  });
  if (!result.ok) return sendError(socket, result.error);

  const room: Room = {
    code,
    state: result.state,
    sockets: new Map(),
    log: [...result.events],
    chat: [],
    gone: new Map(),
    graceTimer: null,
    expiryTimer: null,
  };
  ctx.rooms.set(code, room);
  ctx.playerRooms.set(playerId, code);
  room.sockets.set(playerId, socket);
  conn.room = room;
  conn.playerId = playerId;

  sendJson(socket, { type: 'hello', playerId, roomCode: code });
  sendSnapshot(socket, room, playerId);
  // No pre-existing sockets, so the creation batch has no one to reach.
}

function handleJoinRoom(
  ctx: ServerContext,
  conn: Connection,
  packet: Extract<ClientPacket, { type: 'joinRoom' }>,
  socket: WebSocket,
): void {
  if (conn.room !== null) return sendError(socket, 'already_in_room');
  const code = String(packet.roomCode).trim().toUpperCase();
  const room = ctx.rooms.get(code);
  if (!room) return sendError(socket, 'room_not_found');

  const playerId = randomUUID();
  const result = apply(room.state, { type: 'joinRoom', playerId, playerName: packet.name });
  if (!result.ok) return sendError(socket, result.error);

  room.state = result.state;
  room.log.push(...result.events);
  ctx.playerRooms.set(playerId, code);
  room.sockets.set(playerId, socket);
  conn.room = room;
  conn.playerId = playerId;

  sendJson(socket, { type: 'hello', playerId, roomCode: code });
  sendSnapshot(socket, room, playerId);
  // The joiner's snapshot already reflects the join (and any auto-start);
  // the batch events go to the sockets that were already there.
  broadcast(room, result.events, { except: playerId });
  scheduleGraceCheck(ctx, room);
}

function handleGameIntent(ctx: ServerContext, conn: Connection, packet: ClientPacket, socket: WebSocket): void {
  if (conn.room === null || conn.playerId === null) return sendError(socket, 'not_in_room');
  const room = conn.room;
  const intent = toIntent(packet, conn.playerId);
  if (intent === null) return sendError(socket, 'invalid_packet');

  const result = applyIntentAndBroadcast(ctx, room, intent);
  if (!result.ok) sendError(socket, result.error);
}

/**
 * Apply an engine intent, append its events to the log, and broadcast them
 * privacy-filtered. A round that just ended is the safe point for the issue
 * 11 no-show sweep: seats whose owners are still gone past their grace
 * window are vacated (or, at two seats, the room is closed). Then the fold
 * timer is re-aimed at the next turn owner, who may be gone too.
 */
function applyIntentAndBroadcast(ctx: ServerContext, room: Room, intent: Intent): ApplyResult {
  const result = apply(room.state, intent);
  if (!result.ok) return result;
  room.state = result.state;
  room.log.push(...result.events);
  broadcast(room, result.events);
  if (result.events.some((e) => e.type === 'roundEnded')) vacateNoShows(ctx, room);
  scheduleGraceCheck(ctx, room);
  return result;
}

/**
 * Intentional leave (issue 11): unbind the socket before doing anything else,
 * so its close handler starts no grace window and announces no playerGone —
 * the leave packet is how intent is told apart from an accident. The engine
 * removes the seat (lobby or 3–4 player match); a room that would drop below
 * two seats cannot continue and is torn down with a `roomClosed` notice.
 */
function handleLeave(ctx: ServerContext, conn: Connection, _packet: Extract<ClientPacket, { type: 'leave' }>, socket: WebSocket): void {
  if (conn.room === null || conn.playerId === null) return sendError(socket, 'not_in_room');
  const room = conn.room;
  const playerId = conn.playerId;
  const name = room.state?.players.find((p) => p.id === playerId)?.name ?? playerId;

  if (room.state !== null && room.state.phase !== 'lobby' && room.state.players.length <= 2) {
    conn.room = null;
    conn.playerId = null;
    closeRoom(ctx, room, 'player_left', { name });
    return;
  }

  if (!applyIntentAndBroadcast(ctx, room, { type: 'leave', playerId }).ok) {
    sendError(socket, 'cannot_leave_room');
    return;
  }

  // The seat is gone for good: unbind before closing the socket.
  room.sockets.delete(playerId);
  room.gone.delete(playerId);
  ctx.playerRooms.delete(playerId);
  conn.room = null;
  conn.playerId = null;
  socket.close();

  if (room.state !== null && room.state.players.length === 0) {
    deleteRoom(ctx, room.code); // the last player left the lobby
  }
}

/**
 * Rebind a dropped player's seat to a fresh socket and bring it up to date:
 * `hello`, a `snapshot` (the current view, carrying the log id it covers),
 * every event after the client's `lastEventId` (privacy-filtered), and the
 * room's recent chat. A client that kept its view folds the replayed events
 * into it; a fresh client uses the snapshot and skips the replay.
 */
function handleResume(ctx: ServerContext, conn: Connection, packet: Extract<ClientPacket, { type: 'resume' }>, socket: WebSocket): void {
  const { playerId, lastEventId } = packet;
  if (typeof playerId !== 'string' || typeof lastEventId !== 'number' || !Number.isFinite(lastEventId)) {
    return sendError(socket, 'invalid_resume_packet');
  }
  const code = ctx.playerRooms.get(playerId);
  const room = code !== undefined ? ctx.rooms.get(code) : undefined;
  if (!room || room.state === null || !room.state.players.some((p) => p.id === playerId)) {
    return sendError(socket, 'no_seat_found');
  }

  // If this socket was bound to another seat, that seat is now abandoned —
  // treat it like a drop so it gets its own grace window.
  if (conn.room !== null && conn.playerId !== null && conn.room.sockets.get(conn.playerId) === socket) {
    markSeatGone(ctx, conn.room, conn.playerId);
  }

  // Replace any older socket still holding this seat (e.g. a stale tab).
  const previous = room.sockets.get(playerId);
  if (previous !== undefined && previous !== socket && previous.readyState === WebSocket.OPEN) {
    previous.close();
  }
  room.sockets.set(playerId, socket);
  conn.room = room;
  conn.playerId = playerId;

  // The seat is back: cancel the fold and the room's expiry. Only announce
  // the return if the seat was actually marked gone — a resume that merely
  // replaces a stale but connected socket must not cry "reconnected".
  const wasGone = room.gone.has(playerId);
  room.gone.delete(playerId);
  cancelRoomExpiry(room);
  if (wasGone) announceBack(ctx, room, playerId);

  sendJson(socket, { type: 'hello', playerId, roomCode: room.code });
  sendSnapshot(socket, room, playerId);
  for (let id = Math.max(0, Math.floor(lastEventId) + 1); id < room.log.length; id++) {
    sendJson(socket, { type: 'event', id, event: filterEvent(room.log[id]!, playerId) });
  }
  sendJson(socket, { type: 'chatLog', messages: room.chat });
  scheduleGraceCheck(ctx, room);
}

function handleChat(conn: Connection, packet: Extract<ClientPacket, { type: 'chat' }>, socket: WebSocket): void {
  if (conn.room === null || conn.playerId === null) return sendError(socket, 'not_in_room');
  const room = conn.room;
  const text = typeof packet.text === 'string' ? packet.text.trim() : '';
  if (text.length === 0) return sendError(socket, 'empty_chat');

  const player = room.state?.players.find((p) => p.id === conn.playerId);
  const message: ChatMessage = {
    from: conn.playerId,
    name: player?.name ?? conn.playerId,
    text: text.slice(0, MAX_CHAT_LENGTH),
  };
  room.chat.push(message);
  if (room.chat.length > MAX_CHAT_LINES) room.chat.splice(0, room.chat.length - MAX_CHAT_LINES);

  for (const [, ws] of room.sockets) {
    if (ws.readyState === WebSocket.OPEN) sendJson(ws, { type: 'chat', message });
  }
}

function toIntent(packet: ClientPacket, playerId: string): Intent | null {
  switch (packet.type) {
    case 'playCard': return { type: 'playCard', playerId, which: packet.which };
    case 'choice': return { type: 'choice', playerId, choice: packet.choice };
    case 'nextRound': return { type: 'nextRound', playerId };
    case 'rematch': return { type: 'rematch', playerId };
    default: return null;
  }
}

// ---------------------------------------------------------------------------
// Grace / auto-fold
// ---------------------------------------------------------------------------

/** Remove a seat's live socket and start its grace window. Used by the close
 *  handler, and by a resume that abandons one seat for another. */
function markSeatGone(ctx: ServerContext, room: Room, playerId: string): void {
  room.sockets.delete(playerId);
  room.gone.set(playerId, Date.now() + ctx.graceMs);
  scheduleGraceCheck(ctx, room);
  if (room.sockets.size === 0) scheduleRoomExpiry(ctx, room);
}

/** Tell the table a seat dropped (issue 11) — the away badge's live half. */
function announceGone(ctx: ServerContext, room: Room, playerId: string): void {
  const name = room.state?.players.find((p) => p.id === playerId)?.name ?? playerId;
  for (const [, ws] of room.sockets) {
    if (ws.readyState === WebSocket.OPEN) sendJson(ws, { type: 'playerGone', playerId, name });
  }
}

/** Tell the table a dropped seat is back (issue 11) — excluding its own socket. */
function announceBack(ctx: ServerContext, room: Room, playerId: string): void {
  const name = room.state?.players.find((p) => p.id === playerId)?.name ?? playerId;
  for (const [id, ws] of room.sockets) {
    if (id === playerId) continue;
    if (ws.readyState === WebSocket.OPEN) sendJson(ws, { type: 'playerBack', playerId, name });
  }
}

/**
 * Ensure the room is watching its current turn owner: if they are a dropped
 * player inside their grace window, schedule the fold for when the window
 * expires (immediately if it already has). Clears any pending timer first —
 * only one fold can be pending at a time.
 */
function scheduleGraceCheck(ctx: ServerContext, room: Room): void {
  if (room.graceTimer !== null) {
    clearTimeout(room.graceTimer);
    room.graceTimer = null;
  }
  if (room.state === null || room.state.phase !== 'round') return;
  const turnId = room.state.currentTurn;
  if (turnId === null) return;
  const deadline = room.gone.get(turnId);
  if (deadline === undefined) return; // the turn owner's socket is present
  const remaining = Math.max(0, deadline - Date.now());
  room.graceTimer = setTimeout(() => foldGoneTurnOwner(ctx, room), remaining);
  room.graceTimer.unref(); // a pending grace window must not hold the process open
}

/** Fold the current turn owner if their grace window has fully expired. */
function foldGoneTurnOwner(ctx: ServerContext, room: Room): void {
  room.graceTimer = null;
  if (room.state === null || room.state.phase !== 'round') return;
  const turnId = room.state.currentTurn;
  if (turnId === null) return;
  const deadline = room.gone.get(turnId);
  // Back within the window, or no longer their turn: nothing to do.
  if (deadline === undefined || deadline > Date.now()) return;

  const result = applyIntentAndBroadcast(ctx, room, { type: 'fold', playerId: turnId });
  if (!result.ok) {
    // The engine refuses to fold the last in-round player — the round cannot
    // progress while they are gone, so give them one more grace window to
    // return (a resume cancels the expiry) and reclaim the room otherwise.
    scheduleRoomExpiry(ctx, room);
  }
}

/**
 * The no-show rule (issue 11): once grace has expired and the owner still
 * hasn't returned, the seat is vacated at the next safe point — the end of
 * the current round — using the same engine `leave` as the button. A room
 * that would drop below two seats cannot continue: the remaining player
 * gets a `roomClosed` notice and the room is reclaimed.
 */
function vacateNoShows(ctx: ServerContext, room: Room): void {
  if (room.state === null || room.state.phase === 'lobby') return;
  const now = Date.now();
  for (const playerId of [...room.gone.keys()]) {
    const deadline = room.gone.get(playerId);
    if (deadline === undefined || deadline > now) continue;
    if (!room.state.players.some((p) => p.id === playerId)) continue; // already gone
    if (room.state.players.length <= 2) {
      const name = room.state.players.find((p) => p.id === playerId)?.name ?? playerId;
      closeRoom(ctx, room, 'no_show', { name });
      return;
    }
    if (applyIntentAndBroadcast(ctx, room, { type: 'leave', playerId }).ok) {
      room.gone.delete(playerId);
    }
  }
}

/** Reclaim the room after one more grace window: the last socket left, or the
 *  only in-round player is gone and cannot be folded. */
function scheduleRoomExpiry(ctx: ServerContext, room: Room): void {
  if (room.expiryTimer !== null) return;
  room.expiryTimer = setTimeout(() => {
    room.expiryTimer = null;
    deleteRoom(ctx, room.code);
  }, ctx.graceMs);
  room.expiryTimer.unref();
}

/** Issue 11: a room that can no longer sustain a match gets a terminal notice
 *  on every open socket, then is torn down (which closes those sockets). */
function closeRoom(ctx: ServerContext, room: Room, code: string, params?: WireParams): void {
  for (const [, ws] of room.sockets) {
    if (ws.readyState !== WebSocket.OPEN) continue;
    sendJson(ws, params === undefined ? { type: 'roomClosed', code } : { type: 'roomClosed', code, params });
  }
  deleteRoom(ctx, room.code);
}

function cancelRoomExpiry(room: Room): void {
  if (room.expiryTimer !== null) {
    clearTimeout(room.expiryTimer);
    room.expiryTimer = null;
  }
}

/** Tear a room down for good: timers, socket bindings, and registries. */
function deleteRoom(ctx: ServerContext, code: string): void {
  const room = ctx.rooms.get(code);
  if (!room) return;
  if (room.graceTimer !== null) clearTimeout(room.graceTimer);
  if (room.expiryTimer !== null) clearTimeout(room.expiryTimer);
  for (const ws of room.sockets.values()) ws.close(); // tell the remaining clients
  if (room.state !== null) {
    for (const p of room.state.players) ctx.playerRooms.delete(p.id);
  }
  ctx.rooms.delete(code);
}

// ---------------------------------------------------------------------------
// Broadcasting
// ---------------------------------------------------------------------------

/**
 * Private card payloads (draws, deals, peeks, trades) are public table state —
 * the deck shrinks, a hand is dealt — but the card(s) reach only their owner:
 * everyone else receives the payload nulled. The authoritative log keeps the
 * secret; every client tracks the same public state. Replay uses the same
 * filter, so reconnecting never leaks hidden information.
 */
function filterEvent(event: Event, viewerId: string): Event {
  if (
    (event.type === 'cardDealt' || event.type === 'cardDrawn' || event.type === 'handPeeked')
    && event.playerId !== viewerId
  ) {
    return { ...event, card: null };
  }
  if (event.type === 'handTraded' && event.playerId !== viewerId) {
    return { ...event, cards: null };
  }
  return event;
}

/** Send every (already logged) event to every socket, privacy-filtered. */
function broadcast(room: Room, events: Event[], opts: { except?: string } = {}): void {
  const base = room.log.length - events.length; // events are the log's newest tail
  events.forEach((event, i) => {
    const id = base + i;
    for (const [viewerId, ws] of room.sockets) {
      if (viewerId === opts.except) continue;
      if (ws.readyState !== WebSocket.OPEN) continue;
      sendJson(ws, { type: 'event', id, event: filterEvent(event, viewerId) });
    }
  });
}

/** The current view plus the log id it covers, and who is currently away
 *  (grace-held dropped seats) — the snapshot's half of the away state. */
function sendSnapshot(socket: WebSocket, room: Room, playerId: string): void {
  sendJson(socket, {
    type: 'snapshot',
    view: buildView(room.state!, playerId),
    lastEventId: room.log.length - 1,
    away: [...room.gone.keys()],
  });
}

function sendJson(ws: WebSocket, packet: ServerPacket): void {
  if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(packet));
}

function sendError(ws: WebSocket, code: string, params?: WireParams): void {
  sendJson(ws, params === undefined ? { type: 'error', code } : { type: 'error', code, params });
}

// ---------------------------------------------------------------------------
// Room codes
// ---------------------------------------------------------------------------

/** Four unambiguous uppercase letters; retries on collision. */
const CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ';

function generateRoomCode(registry: Map<string, Room>): string {
  for (let attempt = 0; attempt < 100; attempt++) {
    let code = '';
    for (let i = 0; i < 4; i++) {
      code += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
    }
    if (!registry.has(code)) return code;
  }
  throw new Error('could not allocate a room code');
}
