/**
 * The Love Letter server: Node http serving the client build, plus a raw
 * WebSocket upgrade at `/ws`. The server is a thin relay over the engine:
 * sockets send packets, the server stamps the acting playerId, the engine
 * validates and applies, and the resulting events are broadcast.
 *
 * Room registry: `Map<roomCode, Room>`; a Room holds the authoritative engine
 * state, its sockets, and the event log (used by reconnect replay in ticket 05).
 *
 * On join, a socket receives `hello` + `snapshot` (its private view); events
 * generated by its own join are sent to the pre-existing sockets instead, so
 * the new player never double-applies what the snapshot already contains.
 * Private events (`cardDealt`, `cardDrawn`) go only to the named player.
 */

import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { createServer } from 'node:http';
import { WebSocket, WebSocketServer } from 'ws';
import {
  apply,
  buildView,
  type ClientPacket,
  type Event,
  type GameState,
  type Intent,
  type ServerPacket,
} from '@love-letter/core';
import { serveStatic } from './static.js';

export interface Room {
  code: string;
  state: GameState | null;
  sockets: Map<string, WebSocket>;
  log: Event[];
}

interface Connection {
  room: Room | null;
  playerId: string | null;
}

export interface AppHandle {
  httpServer: Server;
  /** The port actually bound (useful when created with port 0). */
  port: number;
  rooms: Map<string, Room>;
  close(): Promise<void>;
}

export interface AppOptions {
  port?: number;
  /** Directory to serve; pass null to serve nothing (ws-only). */
  staticRoot?: string | null;
}

export async function createApp(options: AppOptions = {}): Promise<AppHandle> {
  const { port = 3001, staticRoot = null } = options;
  const rooms = new Map<string, Room>();

  const httpServer = createServer((req, res) => {
    if (staticRoot !== null) {
      void serveStatic(req, res, staticRoot);
    } else {
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('Not found');
    }
  });

  const wss = new WebSocketServer({ noServer: true });
  httpServer.on('upgrade', (req, socket, head) => {
    const pathname = new URL(req.url ?? '/', 'http://localhost').pathname;
    if (pathname === '/ws') {
      wss.handleUpgrade(req, socket, head, (ws) => wss.emit('connection', ws, req));
    } else {
      socket.destroy();
    }
  });

  wss.on('connection', (socket) => {
    const conn: Connection = { room: null, playerId: null };

    socket.on('message', (raw) => {
      let packet: ClientPacket;
      try {
        packet = JSON.parse(raw.toString()) as ClientPacket;
      } catch {
        sendError(socket, 'invalid JSON');
        return;
      }
      handlePacket(conn, packet, socket, rooms);
    });

    socket.on('close', () => {
      if (conn.room !== null && conn.playerId !== null) {
        conn.room.sockets.delete(conn.playerId);
        // Seat-hold / grace is ticket 05; for now an emptied room is removed.
        if (conn.room.sockets.size === 0) rooms.delete(conn.room.code);
      }
    });
  });

  await new Promise<void>((resolve) => httpServer.listen(port, resolve));
  const address = httpServer.address();
  const actualPort = typeof address === 'object' && address !== null ? address.port : port;

  return {
    httpServer,
    port: actualPort,
    rooms,
    close: () =>
      new Promise<void>((resolve) => {
        for (const room of rooms.values()) {
          for (const ws of room.sockets.values()) ws.close();
        }
        wss.close();
        httpServer.close(() => resolve());
      }),
  };
}

// ---------------------------------------------------------------------------
// Packet handling
// ---------------------------------------------------------------------------

function handlePacket(conn: Connection, packet: ClientPacket, socket: WebSocket, rooms: Map<string, Room>): void {
  switch (packet.type) {
    case 'createRoom': return handleCreateRoom(conn, packet, socket, rooms);
    case 'joinRoom': return handleJoinRoom(conn, packet, socket, rooms);
    case 'playCard':
    case 'choice':
    case 'nextRound':
    case 'rematch':
      return handleGameIntent(conn, packet, socket);
    default:
      return sendError(socket, `unknown packet type: ${String((packet as { type?: unknown }).type)}`);
  }
}

function handleCreateRoom(conn: Connection, packet: Extract<ClientPacket, { type: 'createRoom' }>, socket: WebSocket, rooms: Map<string, Room>): void {
  if (conn.room !== null) return sendError(socket, 'you are already in a room');
  const code = generateRoomCode(rooms);
  const playerId = randomUUID();

  const result = apply(null, {
    type: 'createRoom',
    roomCode: code,
    capacity: packet.capacity as 2 | 3 | 4,
    playerId,
    playerName: packet.name,
  });
  if (!result.ok) return sendError(socket, result.error);

  const room: Room = { code, state: result.state, sockets: new Map(), log: [...result.events] };
  rooms.set(code, room);
  room.sockets.set(playerId, socket);
  conn.room = room;
  conn.playerId = playerId;

  sendJson(socket, { type: 'hello', playerId, roomCode: code });
  sendJson(socket, { type: 'snapshot', view: buildView(result.state, playerId) });
  // No pre-existing sockets, so the creation batch has no one to reach.
}

function handleJoinRoom(conn: Connection, packet: Extract<ClientPacket, { type: 'joinRoom' }>, socket: WebSocket, rooms: Map<string, Room>): void {
  if (conn.room !== null) return sendError(socket, 'you are already in a room');
  const code = String(packet.roomCode).trim().toUpperCase();
  const room = rooms.get(code);
  if (!room) return sendError(socket, 'room not found');

  const playerId = randomUUID();
  const result = apply(room.state, { type: 'joinRoom', playerId, playerName: packet.name });
  if (!result.ok) return sendError(socket, result.error);

  room.state = result.state;
  room.log.push(...result.events);
  room.sockets.set(playerId, socket);
  conn.room = room;
  conn.playerId = playerId;

  sendJson(socket, { type: 'hello', playerId, roomCode: code });
  sendJson(socket, { type: 'snapshot', view: buildView(result.state, playerId) });
  // The joiner's snapshot already reflects the join (and any auto-start);
  // the batch events go to the sockets that were already there.
  broadcast(room, result.events, { except: playerId });
}

function handleGameIntent(conn: Connection, packet: ClientPacket, socket: WebSocket): void {
  if (conn.room === null || conn.playerId === null) return sendError(socket, 'you are not in a room');
  const room = conn.room;
  const intent = toIntent(packet, conn.playerId);
  if (intent === null) return sendError(socket, 'invalid packet');

  const result = apply(room.state, intent);
  if (!result.ok) return sendError(socket, result.error);

  room.state = result.state;
  room.log.push(...result.events);
  broadcast(room, result.events);
}

function toIntent(packet: ClientPacket, playerId: string): Intent | null {
  switch (packet.type) {
    case 'playCard': return { type: 'playCard', playerId, which: packet.which };
    case 'choice': return { type: 'choice', playerId, choice: packet.choice };
    case 'nextRound': return { type: 'nextRound', playerId };
    case 'rematch': return { type: 'rematch', playerId };
    default: return null;
  }
}

// ---------------------------------------------------------------------------
// Broadcasting
// ---------------------------------------------------------------------------

/**
 * Send every event to every socket in the room. The draw/deal/peek events are
 * public (the deck shrinks, a hand is dealt, a Priest looks) but their card
 * payload is private: non-owners receive `card: null`, so the authoritative
 * log keeps the secret while every client tracks the same public table state.
 */
function broadcast(room: Room, events: Event[], opts: { except?: string } = {}): void {
  for (const event of events) {
    for (const [id, ws] of room.sockets) {
      if (id === opts.except) continue;
      if (ws.readyState !== WebSocket.OPEN) continue;
      let payload: Event = event;
      if (
        (event.type === 'cardDealt' || event.type === 'cardDrawn'
          || event.type === 'handPeeked' || event.type === 'handTraded')
        && event.playerId !== id
      ) {
        payload = { ...event, card: null };
      }
      sendJson(ws, { type: 'event', event: payload });
    }
  }
}

function sendJson(ws: WebSocket, packet: ServerPacket): void {
  if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(packet));
}

function sendError(ws: WebSocket, message: string): void {
  sendJson(ws, { type: 'error', message });
}

// ---------------------------------------------------------------------------
// Room codes
// ---------------------------------------------------------------------------

/** Four unambiguous uppercase letters; retries on collision. */
const CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ';

function generateRoomCode(registry: Map<string, Room>): string {
  for (let attempt = 0; attempt < 100; attempt++) {
    let code = '';
    for (let i = 0; i < 4; i++) {
      code += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
    }
    if (!registry.has(code)) return code;
  }
  throw new Error('could not allocate a room code');
}
